# Generated by Django 2.0.6 on 2018-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('L', 'Second Player Wins'), ('W', 'First Player Wins'), ('F', 'First Player to Move'), ('D', 'Draw'), ('S', 'Second Player to Move')], default='F', max_length=1),
        ),
    ]
