# Generated by Django 2.0.6 on 2018-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20180605_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('L', 'Second Player Wins'), ('W', 'First Player Wins'), ('F', 'First Player to Move'), ('S', 'Second Player to Move'), ('D', 'Draw')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
