# Generated by Django 2.0.6 on 2018-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_auto_20180607_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('W', 'First Player Wins'), ('S', 'Second Player to Move'), ('F', 'First Player to Move'), ('L', 'Second Player Wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
